site_name: Rancher Opni
repo_url: https://github.com/rancher/opni
strict: false
theme:
  name: material
  palette:
    primary: purple
  font:
    text: 'Work Sans'
  logo: 'https://github.com/rancher/project-assets/blob/master/logos/opni/icon-opni.png'
  favicon: 'assets/favicon-32x32.png'
#google_analytics:
plugins:
  - search
  - markdownextradata: {}
markdown_extensions:
- codehilite
- admonition
- pymdownx.tabbed
- pymdownx.superfences
- toc:
    permalink: true
nav:
  - index.md
