site_name: Rancher Opni
repo_url: https://github.com/rancher/opni
strict: false
theme:
  name: material
  palette:
    primary: purple
  font:
    text: 'Work Sans'
  logo: 'assets/logo-horizontal-opni.png'
  favicon: 'assets/icon-opni.png'
#google_analytics:
plugins:
  - search
  - markdownextradata: {}
markdown_extensions:
- codehilite
- admonition
- pymdownx.tabbed
- pymdownx.superfences
- toc:
    permalink: true
nav:
  - index.md
  - Installation:
    - install/quickstart.md
    - install/main.md